### ISSUE TITLE
Set decimal places

### ISSUE THREAD

**Issue by dietersiebs** [schlac/hacs-integration-discovergy#9]
Hi,
is it possible to set decimal places for the values in the dashboard of home assistant. At this time there are 6 digits after the comma (f.e. 31234,123456 kWh).

It will better if it is possible to set the number of digits to own values (0, 1, 2, ...).

Regards
Dieter

**Comment by schlac** [comment]
Hi Dieter, sorry for dragging this out. As it turned out my mail rules have not been optimal...

I do see the six figures as well. My assumption is that this simply is what discovergy provides on the API.
While 0.001 Wh surely does surely not provide us much in the real world. I am pretty sure the values are best set on the presenting element within the UI. Some components do use the `decimals: 0` for this. This leaves the values received as is.

Since there is no option panel yet I am not sure how complex this is to add.

Just out of curiosity, what are you monitoring the absolute number for?

**Comment by jpbede** [comment]
As @schlac mentioned, this is how Discovergy provides the data, but I can certainly add an configuration option for it.

**Comment by jpbede** [comment]
I've added this option, along with a configurable update interval, with commit https://github.com/home-assistant/core/pull/54280/commits/7b836b9a24a3d49a780bcb4244ad8d623846245d.

**Comment by dietersiebs** [comment]
Hi together, thank you very much. Meanwhile I'm no langer customer of Discovergy, so I can't test it. But I think ist will be a good thing for other user of the integration.

Best regards and have a good new year
Dieter
